[KAN-8] Added test case to check “Add to cart” functionality
VadimNastoyashchy/cypress-aqa-cource pull request #11
Opened 2024-08-05 16:54 UTC by marynaaa

1. Added Login process to the commands file
2. Added a new test case to check  “Add to cart” functionality, ensuring the website work as expected

2024-08-05 17:19 UTC, Rayman-bat9 commented on cypress/src/pages/CartPage.js
> +    constructor() {
you don't need to write cartContent on the fifth line

2024-08-05 17:22 UTC, Rayman-bat9 commented on cypress/src/pages/ProductPage.js
> +    constructor() {
you don't need to write productDescription on the fifth line

2024-08-05 17:24 UTC, Rayman-bat9 commented on cypress/src/services/productService.js
if you create folder services, maybe it would be worth moving the userServices file to this folder

2024-08-06 06:37 UTC, VadimNastoyashchy requested changes

2024-08-06 06:37 UTC, VadimNastoyashchy commented on cypress/src/components/CartContent.js
> +        cy.get('#tbodyid').should('exist')
In some cases, elements might exist in the DOM structure but be hidden. Better to check if the element is visible.

2024-08-06 06:37 UTC, VadimNastoyashchy commented on cypress/src/components/ProductCard.js
> +        cy.get('.col-lg-9').contains(productName).click()
<img width="386" alt="Screenshot 2024-08-06 at 09 34 27" src="https://github.com/user-attachments/assets/bc5a24d9-52a7-4809-953e-dbd1f5d67ba1">

It's not a good practice to use class for selecting the element. Try to find the unique value of the element
https://docs.cypress.io/guides/references/best-practices

2024-08-06 06:37 UTC, VadimNastoyashchy commented on cypress/src/services/productService.js
> +    return Cypress.env('PRODUCT_NAME') || 'Samsung galaxy s6'
Do we need to store the product name as an env variable?

2024-08-06 18:36 UTC, Rayman-bat9 approved these changes

2024-08-07 05:31 UTC, VadimNastoyashchy approved these changes

2024-08-07 05:31 UTC, merged