[KAN-11]Added test case to check login process
VadimNastoyashchy/cypress-aqa-cource pull request #8
Opened 2024-07-30 09:15 UTC by Rayman-bat9

Added a new test case to verify the login process, ensuring the correct user flow.

2024-07-30 09:18 UTC, marynaaa approved these changes

2024-07-31 09:30 UTC, VadimNastoyashchy requested changes

2024-07-31 09:30 UTC, VadimNastoyashchy commented on cypress/e2e/log-in.cy.js
> +        const homePage = new HomePage()
Find out how to avoid creating new objects

2024-07-31 09:30 UTC, VadimNastoyashchy commented on cypress/e2e/log-in.cy.js
> +            .header.checkUserName('testUser3444')
Find out how to avoid hardcoded values. Maybe it's better to create some kind of UserHandler and use github secrets or variables

2024-07-31 09:30 UTC, VadimNastoyashchy commented on cypress/src/pages/HomePage.js
> +    logInModal = new LogInModal()
Find out how to avoid creating new objects

2024-07-31 09:30 UTC, VadimNastoyashchy commented on cypress/src/modals/BaseModal.js
> +        this.MODAL_FOOTER_CONTAINER = '.modal-footer'
Is this the right place to store different modal containers/selectors?

2024-07-31 09:30 UTC, VadimNastoyashchy commented on cypress/e2e/log-in.cy.js
> +describe('Login and Logout tests', () => {
The test file and the describe file do not match the same flow name.

cypress/e2e/log-in.cy.js
describe('Login and Logout tests' ....

2024-07-31 09:37 UTC, VadimNastoyashchy requested changes

2024-07-31 09:37 UTC, VadimNastoyashchy commented on cypress/src/components/Header.js
> +    }
Do we have a user name instead of a header component?

2024-07-31 09:37 UTC, VadimNastoyashchy commented on cypress/src/components/Header.js
> +    }
sounds like a general button isn't?

2024-07-31 09:37 UTC, VadimNastoyashchy commented on cypress/src/modals/BaseModal.js
> +    }
Is this the right place to store different modal containers/selectors/actions?

2024-08-02 09:35 UTC, VadimNastoyashchy approved these changes

2024-08-02 09:35 UTC, merged